/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as TvetCollegesRouteImport } from './routes/tvet-colleges'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MeRouteImport } from './routes/me'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BursariesRouteImport } from './routes/bursaries'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UniversitiesSlugRouteImport } from './routes/universities_.$slug'
import { Route as TvetCollegesSlugRouteImport } from './routes/tvet-colleges_.$slug'
import { Route as ResultsResultIdRouteImport } from './routes/results.$resultId'
import { Route as JourneyUniversityRouteImport } from './routes/journey.university'
import { Route as JourneyTvetRouteImport } from './routes/journey.tvet'
import { Route as JourneyNsfasRouteImport } from './routes/journey.nsfas'
import { Route as JourneyGrade12RouteImport } from './routes/journey.grade-12'
import { Route as JourneyGrade11RouteImport } from './routes/journey.grade-11'
import { Route as JourneyGrade10RouteImport } from './routes/journey.grade-10'
import { Route as JourneyBursaryRouteImport } from './routes/journey.bursary'
import { Route as JourneySlugRouteImport } from './routes/journey.$slug'
import { Route as CareersSlugRouteImport } from './routes/careers_.$slug'
import { Route as BursariesSlugRouteImport } from './routes/bursaries_.$slug'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth_.update-password'
import { Route as AuthConfirmRouteImport } from './routes/auth_.confirm'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AdminUniversitiesRouteImport } from './routes/admin.universities'
import { Route as AdminTvetRouteImport } from './routes/admin.tvet'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminBursariesRouteImport } from './routes/admin.bursaries'
import { Route as AdminAiImportRouteImport } from './routes/admin.ai-import'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const TvetCollegesRoute = TvetCollegesRouteImport.update({
  id: '/tvet-colleges',
  path: '/tvet-colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BursariesRoute = BursariesRouteImport.update({
  id: '/bursaries',
  path: '/bursaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UniversitiesSlugRoute = UniversitiesSlugRouteImport.update({
  id: '/universities_/$slug',
  path: '/universities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TvetCollegesSlugRoute = TvetCollegesSlugRouteImport.update({
  id: '/tvet-colleges_/$slug',
  path: '/tvet-colleges/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsResultIdRoute = ResultsResultIdRouteImport.update({
  id: '/results/$resultId',
  path: '/results/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyUniversityRoute = JourneyUniversityRouteImport.update({
  id: '/journey/university',
  path: '/journey/university',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyTvetRoute = JourneyTvetRouteImport.update({
  id: '/journey/tvet',
  path: '/journey/tvet',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyNsfasRoute = JourneyNsfasRouteImport.update({
  id: '/journey/nsfas',
  path: '/journey/nsfas',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyGrade12Route = JourneyGrade12RouteImport.update({
  id: '/journey/grade-12',
  path: '/journey/grade-12',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyGrade11Route = JourneyGrade11RouteImport.update({
  id: '/journey/grade-11',
  path: '/journey/grade-11',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyGrade10Route = JourneyGrade10RouteImport.update({
  id: '/journey/grade-10',
  path: '/journey/grade-10',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyBursaryRoute = JourneyBursaryRouteImport.update({
  id: '/journey/bursary',
  path: '/journey/bursary',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneySlugRoute = JourneySlugRouteImport.update({
  id: '/journey/$slug',
  path: '/journey/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers_/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BursariesSlugRoute = BursariesSlugRouteImport.update({
  id: '/bursaries_/$slug',
  path: '/bursaries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth_/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth_/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUniversitiesRoute = AdminUniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTvetRoute = AdminTvetRouteImport.update({
  id: '/tvet',
  path: '/tvet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBursariesRoute = AdminBursariesRouteImport.update({
  id: '/bursaries',
  path: '/bursaries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiImportRoute = AdminAiImportRouteImport.update({
  id: '/ai-import',
  path: '/ai-import',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bursaries': typeof BursariesRoute
  '/careers': typeof CareersRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tvet-colleges': typeof TvetCollegesRoute
  '/universities': typeof UniversitiesRoute
  '/admin/ai-import': typeof AdminAiImportRoute
  '/admin/bursaries': typeof AdminBursariesRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/tvet': typeof AdminTvetRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/bursaries/$slug': typeof BursariesSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/journey/$slug': typeof JourneySlugRoute
  '/journey/bursary': typeof JourneyBursaryRoute
  '/journey/grade-10': typeof JourneyGrade10Route
  '/journey/grade-11': typeof JourneyGrade11Route
  '/journey/grade-12': typeof JourneyGrade12Route
  '/journey/nsfas': typeof JourneyNsfasRoute
  '/journey/tvet': typeof JourneyTvetRoute
  '/journey/university': typeof JourneyUniversityRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/tvet-colleges/$slug': typeof TvetCollegesSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bursaries': typeof BursariesRoute
  '/careers': typeof CareersRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tvet-colleges': typeof TvetCollegesRoute
  '/universities': typeof UniversitiesRoute
  '/admin/ai-import': typeof AdminAiImportRoute
  '/admin/bursaries': typeof AdminBursariesRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/tvet': typeof AdminTvetRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/bursaries/$slug': typeof BursariesSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/journey/$slug': typeof JourneySlugRoute
  '/journey/bursary': typeof JourneyBursaryRoute
  '/journey/grade-10': typeof JourneyGrade10Route
  '/journey/grade-11': typeof JourneyGrade11Route
  '/journey/grade-12': typeof JourneyGrade12Route
  '/journey/nsfas': typeof JourneyNsfasRoute
  '/journey/tvet': typeof JourneyTvetRoute
  '/journey/university': typeof JourneyUniversityRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/tvet-colleges/$slug': typeof TvetCollegesSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bursaries': typeof BursariesRoute
  '/careers': typeof CareersRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tvet-colleges': typeof TvetCollegesRoute
  '/universities': typeof UniversitiesRoute
  '/admin/ai-import': typeof AdminAiImportRoute
  '/admin/bursaries': typeof AdminBursariesRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/tvet': typeof AdminTvetRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/auth_/confirm': typeof AuthConfirmRoute
  '/auth_/update-password': typeof AuthUpdatePasswordRoute
  '/bursaries_/$slug': typeof BursariesSlugRoute
  '/careers_/$slug': typeof CareersSlugRoute
  '/journey/$slug': typeof JourneySlugRoute
  '/journey/bursary': typeof JourneyBursaryRoute
  '/journey/grade-10': typeof JourneyGrade10Route
  '/journey/grade-11': typeof JourneyGrade11Route
  '/journey/grade-12': typeof JourneyGrade12Route
  '/journey/nsfas': typeof JourneyNsfasRoute
  '/journey/tvet': typeof JourneyTvetRoute
  '/journey/university': typeof JourneyUniversityRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/tvet-colleges_/$slug': typeof TvetCollegesSlugRoute
  '/universities_/$slug': typeof UniversitiesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/bursaries'
    | '/careers'
    | '/me'
    | '/privacy'
    | '/terms'
    | '/tvet-colleges'
    | '/universities'
    | '/admin/ai-import'
    | '/admin/bursaries'
    | '/admin/careers'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/subjects'
    | '/admin/tvet'
    | '/admin/universities'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/update-password'
    | '/bursaries/$slug'
    | '/careers/$slug'
    | '/journey/$slug'
    | '/journey/bursary'
    | '/journey/grade-10'
    | '/journey/grade-11'
    | '/journey/grade-12'
    | '/journey/nsfas'
    | '/journey/tvet'
    | '/journey/university'
    | '/results/$resultId'
    | '/tvet-colleges/$slug'
    | '/universities/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bursaries'
    | '/careers'
    | '/me'
    | '/privacy'
    | '/terms'
    | '/tvet-colleges'
    | '/universities'
    | '/admin/ai-import'
    | '/admin/bursaries'
    | '/admin/careers'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/subjects'
    | '/admin/tvet'
    | '/admin/universities'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/update-password'
    | '/bursaries/$slug'
    | '/careers/$slug'
    | '/journey/$slug'
    | '/journey/bursary'
    | '/journey/grade-10'
    | '/journey/grade-11'
    | '/journey/grade-12'
    | '/journey/nsfas'
    | '/journey/tvet'
    | '/journey/university'
    | '/results/$resultId'
    | '/tvet-colleges/$slug'
    | '/universities/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/bursaries'
    | '/careers'
    | '/me'
    | '/privacy'
    | '/terms'
    | '/tvet-colleges'
    | '/universities'
    | '/admin/ai-import'
    | '/admin/bursaries'
    | '/admin/careers'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/subjects'
    | '/admin/tvet'
    | '/admin/universities'
    | '/auth_/callback'
    | '/auth_/confirm'
    | '/auth_/update-password'
    | '/bursaries_/$slug'
    | '/careers_/$slug'
    | '/journey/$slug'
    | '/journey/bursary'
    | '/journey/grade-10'
    | '/journey/grade-11'
    | '/journey/grade-12'
    | '/journey/nsfas'
    | '/journey/tvet'
    | '/journey/university'
    | '/results/$resultId'
    | '/tvet-colleges_/$slug'
    | '/universities_/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BursariesRoute: typeof BursariesRoute
  CareersRoute: typeof CareersRoute
  MeRoute: typeof MeRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TvetCollegesRoute: typeof TvetCollegesRoute
  UniversitiesRoute: typeof UniversitiesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  BursariesSlugRoute: typeof BursariesSlugRoute
  CareersSlugRoute: typeof CareersSlugRoute
  JourneySlugRoute: typeof JourneySlugRoute
  JourneyBursaryRoute: typeof JourneyBursaryRoute
  JourneyGrade10Route: typeof JourneyGrade10Route
  JourneyGrade11Route: typeof JourneyGrade11Route
  JourneyGrade12Route: typeof JourneyGrade12Route
  JourneyNsfasRoute: typeof JourneyNsfasRoute
  JourneyTvetRoute: typeof JourneyTvetRoute
  JourneyUniversityRoute: typeof JourneyUniversityRoute
  ResultsResultIdRoute: typeof ResultsResultIdRoute
  TvetCollegesSlugRoute: typeof TvetCollegesSlugRoute
  UniversitiesSlugRoute: typeof UniversitiesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvet-colleges': {
      id: '/tvet-colleges'
      path: '/tvet-colleges'
      fullPath: '/tvet-colleges'
      preLoaderRoute: typeof TvetCollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bursaries': {
      id: '/bursaries'
      path: '/bursaries'
      fullPath: '/bursaries'
      preLoaderRoute: typeof BursariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/universities_/$slug': {
      id: '/universities_/$slug'
      path: '/universities/$slug'
      fullPath: '/universities/$slug'
      preLoaderRoute: typeof UniversitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvet-colleges_/$slug': {
      id: '/tvet-colleges_/$slug'
      path: '/tvet-colleges/$slug'
      fullPath: '/tvet-colleges/$slug'
      preLoaderRoute: typeof TvetCollegesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$resultId': {
      id: '/results/$resultId'
      path: '/results/$resultId'
      fullPath: '/results/$resultId'
      preLoaderRoute: typeof ResultsResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/university': {
      id: '/journey/university'
      path: '/journey/university'
      fullPath: '/journey/university'
      preLoaderRoute: typeof JourneyUniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/tvet': {
      id: '/journey/tvet'
      path: '/journey/tvet'
      fullPath: '/journey/tvet'
      preLoaderRoute: typeof JourneyTvetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/nsfas': {
      id: '/journey/nsfas'
      path: '/journey/nsfas'
      fullPath: '/journey/nsfas'
      preLoaderRoute: typeof JourneyNsfasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/grade-12': {
      id: '/journey/grade-12'
      path: '/journey/grade-12'
      fullPath: '/journey/grade-12'
      preLoaderRoute: typeof JourneyGrade12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/grade-11': {
      id: '/journey/grade-11'
      path: '/journey/grade-11'
      fullPath: '/journey/grade-11'
      preLoaderRoute: typeof JourneyGrade11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/grade-10': {
      id: '/journey/grade-10'
      path: '/journey/grade-10'
      fullPath: '/journey/grade-10'
      preLoaderRoute: typeof JourneyGrade10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/bursary': {
      id: '/journey/bursary'
      path: '/journey/bursary'
      fullPath: '/journey/bursary'
      preLoaderRoute: typeof JourneyBursaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$slug': {
      id: '/journey/$slug'
      path: '/journey/$slug'
      fullPath: '/journey/$slug'
      preLoaderRoute: typeof JourneySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers_/$slug': {
      id: '/careers_/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bursaries_/$slug': {
      id: '/bursaries_/$slug'
      path: '/bursaries/$slug'
      fullPath: '/bursaries/$slug'
      preLoaderRoute: typeof BursariesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/update-password': {
      id: '/auth_/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/confirm': {
      id: '/auth_/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/universities': {
      id: '/admin/universities'
      path: '/universities'
      fullPath: '/admin/universities'
      preLoaderRoute: typeof AdminUniversitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tvet': {
      id: '/admin/tvet'
      path: '/tvet'
      fullPath: '/admin/tvet'
      preLoaderRoute: typeof AdminTvetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bursaries': {
      id: '/admin/bursaries'
      path: '/bursaries'
      fullPath: '/admin/bursaries'
      preLoaderRoute: typeof AdminBursariesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-import': {
      id: '/admin/ai-import'
      path: '/ai-import'
      fullPath: '/admin/ai-import'
      preLoaderRoute: typeof AdminAiImportRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiImportRoute: typeof AdminAiImportRoute
  AdminBursariesRoute: typeof AdminBursariesRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminTvetRoute: typeof AdminTvetRoute
  AdminUniversitiesRoute: typeof AdminUniversitiesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiImportRoute: AdminAiImportRoute,
  AdminBursariesRoute: AdminBursariesRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminTvetRoute: AdminTvetRoute,
  AdminUniversitiesRoute: AdminUniversitiesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BursariesRoute: BursariesRoute,
  CareersRoute: CareersRoute,
  MeRoute: MeRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TvetCollegesRoute: TvetCollegesRoute,
  UniversitiesRoute: UniversitiesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  BursariesSlugRoute: BursariesSlugRoute,
  CareersSlugRoute: CareersSlugRoute,
  JourneySlugRoute: JourneySlugRoute,
  JourneyBursaryRoute: JourneyBursaryRoute,
  JourneyGrade10Route: JourneyGrade10Route,
  JourneyGrade11Route: JourneyGrade11Route,
  JourneyGrade12Route: JourneyGrade12Route,
  JourneyNsfasRoute: JourneyNsfasRoute,
  JourneyTvetRoute: JourneyTvetRoute,
  JourneyUniversityRoute: JourneyUniversityRoute,
  ResultsResultIdRoute: ResultsResultIdRoute,
  TvetCollegesSlugRoute: TvetCollegesSlugRoute,
  UniversitiesSlugRoute: UniversitiesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
