/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as TvetCollegesRouteImport } from './routes/tvet-colleges'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BursariesRouteImport } from './routes/bursaries'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsResultIdRouteImport } from './routes/results.$resultId'
import { Route as JourneyTvetRouteImport } from './routes/journey.tvet'
import { Route as JourneyNsfasRouteImport } from './routes/journey.nsfas'
import { Route as JourneyGrade12RouteImport } from './routes/journey.grade-12'
import { Route as JourneyBursaryRouteImport } from './routes/journey.bursary'
import { Route as JourneySlugRouteImport } from './routes/journey.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const TvetCollegesRoute = TvetCollegesRouteImport.update({
  id: '/tvet-colleges',
  path: '/tvet-colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BursariesRoute = BursariesRouteImport.update({
  id: '/bursaries',
  path: '/bursaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsResultIdRoute = ResultsResultIdRouteImport.update({
  id: '/results/$resultId',
  path: '/results/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyTvetRoute = JourneyTvetRouteImport.update({
  id: '/journey/tvet',
  path: '/journey/tvet',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyNsfasRoute = JourneyNsfasRouteImport.update({
  id: '/journey/nsfas',
  path: '/journey/nsfas',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyGrade12Route = JourneyGrade12RouteImport.update({
  id: '/journey/grade-12',
  path: '/journey/grade-12',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyBursaryRoute = JourneyBursaryRouteImport.update({
  id: '/journey/bursary',
  path: '/journey/bursary',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneySlugRoute = JourneySlugRouteImport.update({
  id: '/journey/$slug',
  path: '/journey/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/bursaries': typeof BursariesRoute
  '/careers': typeof CareersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tvet-colleges': typeof TvetCollegesRoute
  '/universities': typeof UniversitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/journey/$slug': typeof JourneySlugRoute
  '/journey/bursary': typeof JourneyBursaryRoute
  '/journey/grade-12': typeof JourneyGrade12Route
  '/journey/nsfas': typeof JourneyNsfasRoute
  '/journey/tvet': typeof JourneyTvetRoute
  '/results/$resultId': typeof ResultsResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/bursaries': typeof BursariesRoute
  '/careers': typeof CareersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tvet-colleges': typeof TvetCollegesRoute
  '/universities': typeof UniversitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/journey/$slug': typeof JourneySlugRoute
  '/journey/bursary': typeof JourneyBursaryRoute
  '/journey/grade-12': typeof JourneyGrade12Route
  '/journey/nsfas': typeof JourneyNsfasRoute
  '/journey/tvet': typeof JourneyTvetRoute
  '/results/$resultId': typeof ResultsResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/bursaries': typeof BursariesRoute
  '/careers': typeof CareersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tvet-colleges': typeof TvetCollegesRoute
  '/universities': typeof UniversitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/journey/$slug': typeof JourneySlugRoute
  '/journey/bursary': typeof JourneyBursaryRoute
  '/journey/grade-12': typeof JourneyGrade12Route
  '/journey/nsfas': typeof JourneyNsfasRoute
  '/journey/tvet': typeof JourneyTvetRoute
  '/results/$resultId': typeof ResultsResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/bursaries'
    | '/careers'
    | '/privacy'
    | '/terms'
    | '/tvet-colleges'
    | '/universities'
    | '/admin/dashboard'
    | '/auth/callback'
    | '/journey/$slug'
    | '/journey/bursary'
    | '/journey/grade-12'
    | '/journey/nsfas'
    | '/journey/tvet'
    | '/results/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/bursaries'
    | '/careers'
    | '/privacy'
    | '/terms'
    | '/tvet-colleges'
    | '/universities'
    | '/admin/dashboard'
    | '/auth/callback'
    | '/journey/$slug'
    | '/journey/bursary'
    | '/journey/grade-12'
    | '/journey/nsfas'
    | '/journey/tvet'
    | '/results/$resultId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/bursaries'
    | '/careers'
    | '/privacy'
    | '/terms'
    | '/tvet-colleges'
    | '/universities'
    | '/admin/dashboard'
    | '/auth/callback'
    | '/journey/$slug'
    | '/journey/bursary'
    | '/journey/grade-12'
    | '/journey/nsfas'
    | '/journey/tvet'
    | '/results/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BursariesRoute: typeof BursariesRoute
  CareersRoute: typeof CareersRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TvetCollegesRoute: typeof TvetCollegesRoute
  UniversitiesRoute: typeof UniversitiesRoute
  JourneySlugRoute: typeof JourneySlugRoute
  JourneyBursaryRoute: typeof JourneyBursaryRoute
  JourneyGrade12Route: typeof JourneyGrade12Route
  JourneyNsfasRoute: typeof JourneyNsfasRoute
  JourneyTvetRoute: typeof JourneyTvetRoute
  ResultsResultIdRoute: typeof ResultsResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvet-colleges': {
      id: '/tvet-colleges'
      path: '/tvet-colleges'
      fullPath: '/tvet-colleges'
      preLoaderRoute: typeof TvetCollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bursaries': {
      id: '/bursaries'
      path: '/bursaries'
      fullPath: '/bursaries'
      preLoaderRoute: typeof BursariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$resultId': {
      id: '/results/$resultId'
      path: '/results/$resultId'
      fullPath: '/results/$resultId'
      preLoaderRoute: typeof ResultsResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/tvet': {
      id: '/journey/tvet'
      path: '/journey/tvet'
      fullPath: '/journey/tvet'
      preLoaderRoute: typeof JourneyTvetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/nsfas': {
      id: '/journey/nsfas'
      path: '/journey/nsfas'
      fullPath: '/journey/nsfas'
      preLoaderRoute: typeof JourneyNsfasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/grade-12': {
      id: '/journey/grade-12'
      path: '/journey/grade-12'
      fullPath: '/journey/grade-12'
      preLoaderRoute: typeof JourneyGrade12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/bursary': {
      id: '/journey/bursary'
      path: '/journey/bursary'
      fullPath: '/journey/bursary'
      preLoaderRoute: typeof JourneyBursaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$slug': {
      id: '/journey/$slug'
      path: '/journey/$slug'
      fullPath: '/journey/$slug'
      preLoaderRoute: typeof JourneySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BursariesRoute: BursariesRoute,
  CareersRoute: CareersRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TvetCollegesRoute: TvetCollegesRoute,
  UniversitiesRoute: UniversitiesRoute,
  JourneySlugRoute: JourneySlugRoute,
  JourneyBursaryRoute: JourneyBursaryRoute,
  JourneyGrade12Route: JourneyGrade12Route,
  JourneyNsfasRoute: JourneyNsfasRoute,
  JourneyTvetRoute: JourneyTvetRoute,
  ResultsResultIdRoute: ResultsResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
