/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as TvetCollegesRouteImport } from './routes/tvet-colleges'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BursariesRouteImport } from './routes/bursaries'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneySlugRouteImport } from './routes/journey.$slug'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const TvetCollegesRoute = TvetCollegesRouteImport.update({
  id: '/tvet-colleges',
  path: '/tvet-colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BursariesRoute = BursariesRouteImport.update({
  id: '/bursaries',
  path: '/bursaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneySlugRoute = JourneySlugRouteImport.update({
  id: '/journey/$slug',
  path: '/journey/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bursaries': typeof BursariesRoute
  '/careers': typeof CareersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tvet-colleges': typeof TvetCollegesRoute
  '/universities': typeof UniversitiesRoute
  '/journey/$slug': typeof JourneySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bursaries': typeof BursariesRoute
  '/careers': typeof CareersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tvet-colleges': typeof TvetCollegesRoute
  '/universities': typeof UniversitiesRoute
  '/journey/$slug': typeof JourneySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bursaries': typeof BursariesRoute
  '/careers': typeof CareersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tvet-colleges': typeof TvetCollegesRoute
  '/universities': typeof UniversitiesRoute
  '/journey/$slug': typeof JourneySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bursaries'
    | '/careers'
    | '/privacy'
    | '/terms'
    | '/tvet-colleges'
    | '/universities'
    | '/journey/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bursaries'
    | '/careers'
    | '/privacy'
    | '/terms'
    | '/tvet-colleges'
    | '/universities'
    | '/journey/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/bursaries'
    | '/careers'
    | '/privacy'
    | '/terms'
    | '/tvet-colleges'
    | '/universities'
    | '/journey/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BursariesRoute: typeof BursariesRoute
  CareersRoute: typeof CareersRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TvetCollegesRoute: typeof TvetCollegesRoute
  UniversitiesRoute: typeof UniversitiesRoute
  JourneySlugRoute: typeof JourneySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvet-colleges': {
      id: '/tvet-colleges'
      path: '/tvet-colleges'
      fullPath: '/tvet-colleges'
      preLoaderRoute: typeof TvetCollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bursaries': {
      id: '/bursaries'
      path: '/bursaries'
      fullPath: '/bursaries'
      preLoaderRoute: typeof BursariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$slug': {
      id: '/journey/$slug'
      path: '/journey/$slug'
      fullPath: '/journey/$slug'
      preLoaderRoute: typeof JourneySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BursariesRoute: BursariesRoute,
  CareersRoute: CareersRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TvetCollegesRoute: TvetCollegesRoute,
  UniversitiesRoute: UniversitiesRoute,
  JourneySlugRoute: JourneySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
